### ISSUE TITLE
Refund transport available even without transport

### ISSUE THREAD

**Issue by 11132113** [tukkek/javelin#13]
Using the refund without transport crash the game:

`
null (class java.lang.NullPointerException)
javelin.view.screen.town.TransportScreen.select(TransportScreen.java:63)
javelin.view.screen.town.SelectScreen.select(SelectScreen.java:126)
javelin.view.screen.town.SelectScreen.processinput(SelectScreen.java:108)
javelin.view.screen.town.SelectScreen.show(SelectScreen.java:67)
javelin.view.screen.town.TownScreen.select(TownScreen.java:58)
javelin.view.screen.town.SelectScreen.select(SelectScreen.java:126)
javelin.view.screen.town.SelectScreen.processinput(SelectScreen.java:108)
javelin.view.screen.town.SelectScreen.show(SelectScreen.java:67)
javelin.view.screen.town.SelectScreen.show(SelectScreen.java:69)
javelin.view.screen.town.SelectScreen.show(SelectScreen.java:69)
javelin.view.screen.town.TownScreen.<init>(TownScreen.java:47)
javelin.model.world.location.town.Town.interact(Town.java:396)
javelin.view.screen.WorldScreen.react(WorldScreen.java:415)
javelin.controller.action.world.WorldMove.perform(WorldMove.java:103)
javelin.view.screen.WorldScreen.convertEventToAction(WorldScreen.java:160)
javelin.view.screen.WorldScreen.humanTurn(WorldScreen.java:132)
javelin.view.screen.BattleScreen.step(BattleScreen.java:181)
javelin.view.screen.WorldScreen.step(WorldScreen.java:222)
javelin.JavelinApp.loop(JavelinApp.java:128)
javelin.JavelinApp.run(JavelinApp.java:112)
java.lang.Thread.run(Unknown Source)
`

**Comment by tukkek** [comment]
Fixed. I'll let you know on #11 when a new version is out for download.

I hope you don't think I'm too incompetent - things like these happen because the code that was already written/tested ends up becoming "wrong" (producing errors) after other changes elsewhere. Since the game is too big I can't test the entire game after such changes are made and have to rely on the help of others or when I myself come across these problems during play. As I spend more time working on the game than playing mistakes like this slip by... 

I could write automated test to automatically test the entire game for me instead but that also means a lot more work and constant updating for the tests :P Right now I just want to get to 2.0 as fast as I can so these things happen...

Anyway thanks again, just letting you know that "simple" bugs like aren't pure incompetence - just a result of a project that is always changing and is too big to manually test by myself. It was certainly working when I wrote that screen at first :D (the exact source of the problem is a field who used to hold a "null" Enum object and now just holds a null value instead, if you're a programmer yourself...)
