### ISSUE TITLE
Crash during combat: couldn't determine outcome

### ISSUE THREAD

**Issue by 11132113** [tukkek/javelin#14]
Here's the log:

```
Couldn't determine outcome: 0.83038557 (class java.lang.RuntimeException)
javelin.controller.action.Action.outcome(Action.java:141)
javelin.view.screen.BattleScreen.computerTurn(BattleScreen.java:350)
javelin.view.screen.BattleScreen.humanTurn(BattleScreen.java:220)
javelin.view.screen.BattleScreen.step(BattleScreen.java:181)
javelin.view.screen.BattleScreen.mainLoop(BattleScreen.java:166)
javelin.controller.exception.battle.StartBattle.battle(StartBattle.java:65)
javelin.JavelinApp.loop(JavelinApp.java:137)
javelin.JavelinApp.run(JavelinApp.java:112)
java.lang.Thread.run(Unknown Source)
```

Was running with:

```
ai.maxsecondsthinking=0.1
ai.maxthreads=1
ai.cache=false
ui.messagedelay=0.75
```

**Comment by tukkek** [comment]
Thank you, bugs like these are a big problem because I need more information to work on them. It may sound difficult at first but with time people usually are able to tell me things like "this only happens when a monster has breath weapons" or flying, or a certain spell, etc.

Unfortunately there is no easy way to make this type of bug (that happens inside the artificial intelligence system) produce more information because this would make the AI a lot slower, which is not acceptable. The AI system is very sensitive to any change so asking it to provide lots of information during an error would be a huge problem.

So let me know if you can identify which types of enemies at least were involved in this battle and if it happens from time to time or just when certain types of enemies are present. I'll improve the error message a little bit for the next version.

Anyway bugs during battle are less of a problem because they don't happen very often (for me at least) and don't completely ruin your game. Of course, if you can provide more information I'll look into it nonetheless!

**Comment by 11132113** [comment]
This error is frequent in my current save (see issue #15 for save file).

Changing ai.maxthread, ai.maxsecondsthinking to higher values doesn't remove the problem.
Working on finding common factor in ennemies.
Issue is still present on new games.
Issue doesn't seem to appear when vs only 1 ennemy.

**Comment by tukkek** [comment]
Have been able to reproduce this, as it does occur quite frequently. This is most certainly a result of recent tweaks in the AI system while fixing things, improving speed and allowing player units to be **A**utomated as well. This should be a very small change to solve this problem but identifying and testing it are not necessarily easy.

**Comment by tukkek** [comment]
Yes, I seem to have fixed it! It was part reverting recent changes back to their former state (without losing improvements), part fixing new bugs and a lot of testing! Still if you can help test some more it would be very helpful since my testing hasn't been exhaustive. If all goes well I'll probably release 1.6 next friday!

Here is the download link with the updated version https://github.com/tukkek/javelin/releases/download/1.6b/javelin.zip

Really - thank you. Your careful feedback has allowed me to make the game a lot better, as you can see :) I'm very glad that I decided to make a beta release and that you came through in helping with it!
