### ISSUE TITLE
Ennemy have the wrong challenge level

### ISSUE THREAD

**Issue by 11132113** [tukkek/javelin#15]
Ennemy town guarded by:

2x Azer (challenge lvl 275, stats in the thousands)
3x Doppleganger (challenge lvl 625, stats in the thousands)
1x Eagle (challenge rating 1, normal stats)

Vs player party:

War pony (challenge lvl 26)
Svirfneblin (challenge lvl 13)
Wood elf (challenge lvl 3)

Fight was marked as "easy".
World was 162 days old.
Closing the game and launching the same fight again fixed the challenge lvls (5, 5 and 1).

**Comment by tukkek** [comment]
Sounds like a cloning problem (cloning is when the game picks the Doppleganger stats and "clones" it 3 times to create 3 different Dopplegangers, for example). I have seen something similar happen but still haven't figured out what is causing it. Since it happens only rarely its not easy to study without knowing the cause.

At least is good that you opened this because I know for sure it's a recurring bug and not something that happened just once in special occasions (it happened to me in a Dungeon so I thought this was a Dungeon problem, which it isn't because for you it happened in a Town).

I'll take a look at cloning modifications since 1.5 to see if anything stands out. Let me know if you notice something else.

**Comment by tukkek** [comment]
Unfortunately nothing relevant to cloning has changed since 1.5 but I'm sure it's a cloning issue. If next time you can tell me which stats are in the thousands it would help a lot. I'll keep an eye here as well.

The one time I noticed this it was speed that was very high - let me know if it is the same for you since it can help me locate the problem.

**Comment by tukkek** [comment]
Also if this happens again it would help if you could see the spells you and the enemies have. To see enemy spells just press x and move the cursor to the enemy's location, spells should appear on the sidebar.

**Comment by 11132113** [comment]
The bug appears every other time for this town on this particular save (when reloading it).

Not every ennemy is bugged (eagle is never)
Stats boosted vary from one time to the other
Every bugged ennemy has the same stats boosted
Effect of the boost vary from an ennemy to the other


Here is the save (it's a rar file renamed because github accept zip only).
[javelin.zip](https://github.com/tukkek/javelin/files/342969/javelin.zip)
Town in question is the closest north.

**Comment by tukkek** [comment]
Hi just letting you know I wasn't able to load your save game, probably because I made further changes in the code here. Also I haven't tested if Windows save files (yours) work on Linux (vice-versa). It would be nice to test this in the near future, so if you can please send me a save file again once I upload a new version I'd appreciate it!

Meanwhile I'll be testing this manually, let you know once I have any news.

**Comment by tukkek** [comment]
Fixed. As I implied it was a problem with cloning and spells - before a spell was being cast the Combatant was cloned but not the underlying Monster. This again resulted from the CastSpell action not being updated after improvements on the cloning system.

I'll try to fix #14 before uploading a new version so that the game is more stable.
