### ISSUE TITLE
Crash if cart goes above 100% load

### ISSUE THREAD

**Issue by 11132113** [tukkek/javelin#18]
Buy cart -> draft creatures until above 100% load -> exit town -> crash

```
[Ljava.lang.Object; cannot be cast to [Ljavelin.model.unit.Combatant; (class java.lang.ClassCastException)
javelin.model.unit.transport.Transport.getspeed(Transport.java:72)
javelin.model.unit.Squad.speed(Squad.java:542)
javelin.view.screen.WorldScreen.updateplayerinformation(WorldScreen.java:277)
javelin.view.screen.WorldScreen.step(WorldScreen.java:216)
javelin.JavelinApp.loop(JavelinApp.java:127)
javelin.JavelinApp.run(JavelinApp.java:112)
java.lang.Thread.run(Unknown Source)
```

**Comment by tukkek** [comment]
Fixed!

Problem here is I tried to use some fancy Java 8 stuff instead of going with the basics. Not sure why it worked here and not for you but anyways I rewrote it back to "normal Java" and it works fine and is less code and easier to read now. Anyway I did find out another bug with movement transport speed and improved a few edge conditions (concerning the % display of load) so thank you very much, once again.
