### ISSUE TITLE
Crash on entering hostile Settlement

### ISSUE THREAD

**Issue by Spiralrazor369** [tukkek/javelin#293]
23dffaab (HEAD -> 1.7) Fix #288 (recruit on guild with rubies)
System: Windows 10 10.0 amd64

Index 0 out of bounds for length 0 (class java.lang.IndexOutOfBoundsException)
java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
java.base/java.util.Objects.checkIndex(Objects.java:373)
java.base/java.util.ArrayList.get(ArrayList.java:427)
javelin/javelin.old.RPG.pick(RPG.java:47)
javelin/javelin.controller.content.fight.mutator.Waves.checkend(Waves.java:93)
javelin/javelin.controller.content.fight.mutator.Waves.draw(Waves.java:101)
javelin/javelin.controller.exception.battle.StartBattle.battle(StartBattle.java:53)
javelin/javelin.JavelinApp.loop(JavelinApp.java:102)
javelin/javelin.JavelinApp.run(JavelinApp.java:81)
java.base/java.lang.Thread.run(Thread.java:832)

**Comment by tukkek** [comment]
I have just tried every Settlement in three different Worlds and could not reproduce this. I will try some more but if it happens again please include your save game file as well so it's easier to trigger and debug.

**Comment by tukkek** [comment]
I have created a new automated test case to check this (`TestWaves`) and have reproduced and fixed it. I have made two changes:

1. Allow Haunt Waves to not mach the exact target EL because, even though the minimum possible EL is determined beforehand, it may still be difficult to generate an exact EL - either because the available enemies make that difficult or impossible or because the Encounter Generator is not deterministically going through all possible combinations and gives up after so many tries. As such, if a Wave doesn't find an Encounter for that EL, it will now try the next-best thing, favoring lower ELs first over higher ELs.
2. Global Haunt minimum difficulty has been bumped to Mid Tier (starting at EL6). This removes the vast majority of offenders that require Wave EL adjustment. It is sad to lose early-game-viable Haunts but since there aren't many very low-level creatures, not many Haunts could generate 4 waves of low-level enemies anyway, so the change is ultimately quite small. Thematically, Haunts work best starting as Mid tier "raids" too.

Possible things to look into to have the widest possible EL range for Haunts:
* Having more creatures with very low CR might help but since each Haunt has its own set of valid units, that's hardly a global solution.
* Testing a deterministic Encounter Generator that explores all possibilities. That could be extremely slow though (unless used only when the default one fails) and is probably not worth the effort for this use-case alone.
* Adding some intelligence to Haunts so that lower-level instances will limit the maximum number or waves.

With the current fix, only 3% of the overall waves need any EL adjustment at all, almost all of them being a ±1. Only 0.4% of Waves require a ±2 adjustment.
